### ISSUE TITLE
Where is the CVWrapper.process function?

### ISSUE THREAD

**Issue by lucychen0103** [foundry/OpenCVSwiftStitch#25]
I've been searching and I can't seem to find it, where does the "CVWrapper.process" in the line
let stitchedImage:UIImage = CVWrapper.process(with: images as! [UIImage]) as UIImage
lead to?

**Comment by foundry** [comment]
I think you mean [the line](https://github.com/foundry/OpenCVSwiftStitch/blob/5faab61e89759046ec44f95cc1d4875936106ce8/SwiftStitch/SwViewController.swift#L54)

`let stitchedImage:UIImage = CVWrapper.process(with: imageArray as! [UIImage]) as UIImage`

which, following your comment, i have [just simplifed to](https://github.com/foundry/OpenCVSwiftStitch/blob/d1e26cb89d76eaf64f24a83fc0571f915337c721/SwiftStitch/SwViewController.swift#L54)

`let stitchedImage:UIImage = CVWrapper.process(with: imageArray)`

it calls this [`Obective-C` method](https://github.com/foundry/OpenCVSwiftStitch/blob/d1e26cb89d76eaf64f24a83fc0571f915337c721/SwiftStitch/CVWrapper.h#L18):

`+ (UIImage*) processWithArray:(NSArray<UIImage*>*)imageArray;`

The difference in syntax is due to the way that Swift translates Objective-C method calls.

**Comment by foundry** [comment]
Update: following your suggestion, I have renamed the CVWrapper class method:

`+ (UIImage*) processWithImages:(NSArray<UIImage*>*)images;`
