### ISSUE TITLE
Doesn't currently compile, Linker errors

### ISSUE THREAD

**Issue by briancordanyoung** [foundry/OpenCVSwiftStitch#3]
I'm excited to learn OpenCV and your project looked like a good place to get started.  After running pod install, I tried to compile the app and ran in to linker errors.  I'm not used to working with C++.   Do you know how to get past these errors?

Using OpenCV (2.4.10)

ERRORS:

Undefined symbols for architecture arm64:
  "_jpeg_free_small", referenced from:
      _free_pool in opencv2(jmemmgr.o)
      _self_destruct in opencv2(jmemmgr.o)
  "_jpeg_mem_available", referenced from:
      _realize_virt_arrays in opencv2(jmemmgr.o)
  "_jpeg_free_large", referenced from:
      _free_pool in opencv2(jmemmgr.o)
  "_jpeg_open_backing_store", referenced from:
      _realize_virt_arrays in opencv2(jmemmgr.o)
  "_jpeg_get_large", referenced from:
      _alloc_large in opencv2(jmemmgr.o)
      _alloc_barray in opencv2(jmemmgr.o)
  "_jpeg_mem_term", referenced from:
      _jinit_memory_mgr in opencv2(jmemmgr.o)
      _self_destruct in opencv2(jmemmgr.o)
  "_jpeg_mem_init", referenced from:
      _jinit_memory_mgr in opencv2(jmemmgr.o)
  "_jpeg_get_small", referenced from:
      _jinit_memory_mgr in opencv2(jmemmgr.o)
      _alloc_small in opencv2(jmemmgr.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by foundry** [comment]
Hello Brian. It seems the latest version of OpenCV (2.4.10) breaks the app. I have updated the podfile to point to the latest working version, v 2.4.9.1. That should fix your issues. Take care to reinstall a fresh copy and re-run pod install.

**Comment by briancordanyoung** [comment]
Awesome.  Thanks for tracking that down.

**Comment by sfr106** [comment]
The links in the current podfiles are broken... error 404.

**Comment by varunramani** [comment]
So here's a little workaround. The problem is because the XCode project is unable to link to the libjpeg.a library. So thats why you get the above errors when you compile the project. 

Follow these steps : 

1. Go to : [[http://sourceforge.net/projects/libjpeg-turbo/files/1.4.0/]] and download the  libjpeg-turbo-1.4.0.dmg (3.8 MB) file.
2. Install the package. Once its done you will find the installed files under this path : */opt/libjpeg-turbo/lib*
3. Open up your terminal and type the following command : *lipo -info /opt/libjpeg-turbo/lib/libjpeg.a*
4. If the terminal shows the following the output after running the command then it means, you can use the library for your iOS project(armv7/armv7s) 
   * Architectures in the fat file: /opt/libjpeg-turbo/lib/libturbojpeg.a are: i386 x86_64 armv6 armv7 armv7s arm64* 
5. Use finder to navigate to : /opt/libjpeg-turbo/lib and copy libjpeg.a and place it in your project folder.
6. Head over to your XCode project -> Click on Project Name -> Targets -> General -> Linked frameworks and libraries -> Click on the add button placed at the bottom -> include the libjpeg.a file
7. Compile the project. It shouldn't show any more linker errors.

**Comment by foundry** [comment]
Please don't do this. The pod is working fine. Brian's errors were due to issues with a particular build of openCV. There were also issues with  unreliable links to openCV in the original podfile. This is now fixed: we are self-hosting a known good version of openCV. I have just tested this with Xcode 6.3 (updated code to Swift 1.2) and it has no issues that I can see.
