### ISSUE TITLE
OpenCV2/opencv.hpp not found

### ISSUE THREAD

**Issue by felipecocco** [foundry/OpenCVSwiftStitch#9]
I hate to be asking such a simple question, but I seem to be getting tripped up by something rather trivial -- I keep getting an "opencv2/opencv.hpp" is not found error. What I've done so far:
1)Downloaded your proj. and opened in XCode
2)Downloaded OpenCV 3.0 from the link you supplied
3)Dragged the framework into the Frameworks folder of the project
4)Commented out the lines of stitching.cpp according to your instruction above.
5)Noticed that OpenCV was already in a "required" state in the build phase for the project.

What'd I miss?

**Comment by kgoedecke** [comment]
Have you tried OpenCV 2?

**Comment by felipecocco** [comment]
Sorry I'm not quite sure what you mean. Should I try it with the 2.X.X version of the download?

**Comment by kgoedecke** [comment]
yes!

**Comment by felipecocco** [comment]
Well, that worked beautifully! Now off to go learn this thing. Thank you so much for such a great example project.

And, when I have nothing better to do, I'll try to understand what is going on with the 3.X.X version! Thank you for your help

**Comment by foundry** [comment]
Hi felipecocco. From your notes, it looks as if you may have changed the name of the openCV framework. It MUST be named "opencv2.framework". Otherwise the path references will break. Unfortunately openCV v.3 has retained the pathnames of openCV v.2.x.x, so it has to retain the name 'opencv2.framework'. This can get a little confusing!

Please let me know if this fixes your installation. 

There are also minor issues with XCode 7, ios9 and Swift 2 that you may encounter if you are using that environment. In patcular, if you open the project in XCode 7, you will be asked if you want to convert to the latest Swift syntax. You do _not_ have to do this to run the project. If you _do_ convert, the process will also turn on Bitcode. Then the project will not compile, as the openCV framework is not bitcode-enabled.  You can disable Bitcode in the target's build settings->build options->Enable Bitcode, then you should be ok.

As kgoedecke has pointed out, you can also try the 2.x.x version instead - then you should use Cocoapods and the incuded podfile to manage the process. v2.x.x delivers a better quality result than v3 on the supplied images.

**Comment by felipecocco** [comment]
I maintained the "opencv2.framework" name -- that's what appeared in XCode. I am using XCode 7 and it did prompt me to change the syntax, but I declined. I will try again tonight from scratch and perhaps some obvious omission of mine will become clear -- if I run into this again I put the project up here so you can take a look
